### ISSUE TITLE
Sentence input with Timer

### ISSUE THREAD

**Issue by JamesLanceQ** [CardenesMa/SummerCodeJam#1]
Website page component that handles an updating timer to input a sentence that completes the prompt. For now the timer could be created on a later version after the mvp if necessary. If you want to go ahead and add the optional functionality feel free.

**Comment by PhantomLel** [comment]
I will take this

**Comment by PhantomLel** [comment]
Ok this is what I came up with.
![component](https://user-images.githubusercontent.com/84487477/180664415-a097bf86-3216-4635-bffa-b90b7ffccacc.png)

**Comment by PhantomLel** [comment]
The timer is by the submit button

**Comment by JamesLanceQ** [comment]
Looks good, do you know how to a do pr?

**Comment by PhantomLel** [comment]
Yes. Are we just doing styles and basic js right now then implementing the websockets later?
